### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by JustoRago** [asdt560/Portfolio#9]
Leave your feedback here.

**Comment by Miliyonayalew** [comment]
It looks great 👍 💯 , I think it's better if you decrease the animation font size for headline part in the mobile version because it scales out a little bit from the mobile screen.

**Comment by KanzaTahreem** [comment]
Great work and effort you put into this project so far. Keep it up! 💪💯


- You have done a great job with the animations to improve the browsing experience in the desktop version 💻


Cheers and Happy coding!👏👨‍💻

**Comment by PedroH-Neves** [comment]
You did a great job 👍 💯 , i think that would be better if you let your works section centralized in the desktop version because its letting a gap in the right side
